### ISSUE TITLE
README.md: Preview images are not available due to redirect of http://demo.tileserver.org

### ISSUE THREAD

**Issue by pathmapper** [openmaptiles/klokantech-basic-gl-style#10]
![image](https://user-images.githubusercontent.com/20856381/32696326-d65eda06-c775-11e7-87d3-ce3d5900c525.png)

**Comment by keosak** [comment]
Change the preview to use maps.tilehosting.com with key jrAEbKm36x6XabJkeiBU.

**Comment by jirik** [comment]
@petrsloup Can we use https://github.com/klokantech/thumbnail-gl for generating previews?

**Comment by jirik** [comment]
Closed by https://github.com/openmaptiles/klokantech-basic-gl-style/commit/953fe4f370a2b0a7bf53fdbc5a4d1fee0d145198
