### ISSUE TITLE
place = island too visible

### ISSUE THREAD

**Issue by nlehuby** [openmaptiles/klokantech-basic-gl-style#12]
In the following picture :
* Saint-Maur des Fossés, Créteil, Joinvill-le-Pont are towns (layer place)
* Île de la Gruyère (layer place) is a small island. It should not be present at this zoom layer
![screenshot-2017-12-7 world maps you can self-host - powered by free openstreetmap vector tiles and open-source software](https://user-images.githubusercontent.com/919962/33729125-f1cde348-db7c-11e7-815b-2fc4a98a1f00.png)

In the following picture :
* Chessy and Montevrain are towns
* Wilderness Island is a smal island in Disneyland Park. It should not be present at this zoom layer
![screenshot-2017-12-7 world maps you can self-host - powered by free openstreetmap vector tiles and open-source software 1](https://user-images.githubusercontent.com/919962/33729124-f1b4e6a4-db7c-11e7-9935-4653ffdf7d69.png)

**Comment by mcm-jyl** [comment]
Île de la Gruyère: it was tagged as island, it should be an islet => OSM data had to be corrected.
Wilderness Island: was corrected just after you mentioned the bug.

IMHO this can be closed.

**Comment by nlehuby** [comment]
thanks @mcm-jyl :+1:
