### ISSUE TITLE
tunnel=culvert

### ISSUE THREAD

**Issue by frodrigo** [openmaptiles/klokantech-basic-gl-style#13]
The tag tunnel=culvert is not supported and waterway appear as standard waterway. which is ugly for culvert streams or rivers way in city.

**Comment by jirik** [comment]
@frodrigo PR is welcome. I guess it can be implemented when https://github.com/openmaptiles/openmaptiles/pull/393 is merged.

**Comment by jirik** [comment]
@frodrigo See also https://github.com/openmaptiles/openmaptiles/issues/360#issuecomment-357928892 , so we probably need another schema improvement before this one.

**Comment by frodrigo** [comment]
What do you thing about this:
![image](https://user-images.githubusercontent.com/1785486/35012599-98099b9c-fb0a-11e7-80c1-c745f1d57b2d.png)
![image](https://user-images.githubusercontent.com/1785486/35012602-9a863826-fb0a-11e7-868f-2b5dcf1b8fdc.png)

(cc @nlehuby )

I will made PR to openmaptiles and to klokantech-basic-gl-style

**Comment by jirik** [comment]
Looks good to me, please make PR.
