### ISSUE TITLE
Contents of the sprite location

### ISSUE THREAD

**Issue by schulm** [openmaptiles/klokantech-basic-gl-style#17]
Does this style use sprites? They were referenced in the style.json.

**Comment by jirik** [comment]
It uses one sprite for oneway road currently. However as you see in #18 , it will be probably removed.

**Comment by melroy89** [comment]
How can I use my own sprites?

**EDIT:** https://github.com/klokantech/tileserver-gl/issues/279#issuecomment-414561379
