### ISSUE TITLE
Tisza -  missing river -   z8-z11  

### ISSUE THREAD

**Issue by ImreSamu** [openmaptiles/klokantech-basic-gl-style#3]
the  [Tisza](https://en.wikipedia.org/wiki/Tisza)   river ( Near [Szeged](https://en.wikipedia.org/wiki/Szeged)  ) is only show in the z12 
  
Missing from  z8-z11    

### z11
https://openmaptiles.github.io/klokantech-basic-gl-style/#11.32/46.2154/20.2069
![image](https://cloud.githubusercontent.com/assets/2217320/21589984/c9b648ea-d0f7-11e6-8731-17f550f7ac04.png)

### z12
![image](https://cloud.githubusercontent.com/assets/2217320/21589995/eb648dbc-d0f7-11e6-89b9-1c4587e87aa4.png)

###  side note - the ideal case in  >z6
 ( but I know -  it is not so easy ... )

![image](https://upload.wikimedia.org/wikipedia/commons/7/79/Thiz_river.jpg)
https://en.wikipedia.org/wiki/Tisza#/media/File:Thiz_river.jpg

**Comment by ImreSamu** [comment]
the same in Vienna  (  river: Donau )
https://openmaptiles.github.io/klokantech-basic-gl-style/#11/48.1617/16.5046

![image](https://cloud.githubusercontent.com/assets/2217320/21590090/ecd07db8-d0f8-11e6-8b4f-b6b4fd846584.png)

**Comment by klokan** [comment]
This seems to be a serious bug @lukasmartinelli

**Comment by ImreSamu** [comment]
other test cases : 

Lisbon (Portugal)  z11  vs  z12  ( river )  
*  https://openmaptiles.github.io/klokantech-basic-gl-style/#11.76/38.6707/-9.0776
*  https://openmaptiles.github.io/osm-bright-gl-style/#11.64/38.6455/-9.0898/7.2/26

London:   z11  vs  z12  ( river )  
* https://openmaptiles.github.io/klokantech-basic-gl-style/#11.69/51.4745/0.4458
* https://openmaptiles.github.io/osm-bright-gl-style/#11.44/51.4634/0.3738/7.2/26

**Comment by pathmapper** [comment]
@ImreSamu this issue is solved and could be closed

**Comment by jirik** [comment]
@pathmapper Thanks for notification, closing
