### ISSUE TITLE
Parks

### ISSUE THREAD

**Issue by klokan** [openmaptiles/klokantech-basic-gl-style#4]
Please see the appearance of the green areas for example around Washington, DC in:

New KlokanTech Basic Style:
https://openmaptiles.github.io/klokantech-basic-gl-style/#11.89/38.8924/-77.0166

Old KlokanTech Basic Style:
http://klokantech.tilehosting.com/styles/basic/?key=tXme5cuqgrCqdPoZHqyn#9.75/38.7970/-76.9164

Or compare with other existing maps, please, such as 
https://www.google.com/maps/place/Washington,+DC,+USA/@38.8660799,-77.0858514,11.54z/data=!4m5!3m4!1s0x89b7c6de5af6e45b:0xc2524522d4885d2a!8m2!3d38.9071923!4d-77.0368707?hl=en

**Comment by lukasmartinelli** [comment]
Grass and park layer was not styled.
However there are less grass/wood areas shown as before due to the more agressive dropping of small polygons.
