### ISSUE TITLE
Roads

### ISSUE THREAD

**Issue by klokan** [openmaptiles/klokantech-basic-gl-style#5]
Please see the appearance of the streets while zooming for example around Washington, DC in:

New KlokanTech Basic Style:
https://openmaptiles.github.io/klokantech-basic-gl-style/#11.89/38.8924/-77.0166

Old KlokanTech Basic Style:
http://klokantech.tilehosting.com/styles/basic/?key=tXme5cuqgrCqdPoZHqyn#9.75/38.7970/-76.9164

Or compare with other existing maps, please, such as 
https://www.google.com/maps/place/Washington,+DC,+USA/@38.8660799,-77.0858514,11.54z/data=!4m5!3m4!1s0x89b7c6de5af6e45b:0xc2524522d4885d2a!8m2!3d38.9071923!4d-77.0368707?hl=en

**Comment by lukasmartinelli** [comment]
Roads had the wrong filters. Was a good test for the Maputnik inspection mode :)
![screenshot from 2017-01-04 12-14-39](https://cloud.githubusercontent.com/assets/1288339/21640757/8ff29074-d277-11e6-8553-f1d99d594b66.png)
