### ISSUE TITLE
Different colours for waters

### ISSUE THREAD

**Issue by daliborjanak** [openmaptiles/klokantech-basic-gl-style#6]
In the style are different colors for rivers and water areas. Rivers are lighter. On lakes and large rivers is a visible river line. Is it possible to assign the same color to a river? Make it sense? Se screenshot:
![image](https://cloud.githubusercontent.com/assets/1891090/21674191/f083c5e2-d32c-11e6-8726-3af7dafe9b88.png)

**Comment by daliborjanak** [comment]
Minimally add water areas over rivers...

**Comment by daliborjanak** [comment]
@lukasmartinelli

**Comment by lukasmartinelli** [comment]
Thanks :) :+1:
